#! /bin/sh

set -e

echo "=> Installing environment temperature logger...\n"
sudo cp script/env-temp.py /usr/local/bin/
sudo chmod +x /usr/local/bin/env-temp.py

echo "=> Starting environment temperature logger...\n"
sudo cp script/env-temp.sh /etc/init.d/
sudo chmod +x /etc/init.d/env-temp.sh

sudo update-rc.d env-temp.sh defaults
sudo /etc/init.d/env-temp.sh start

echo "Environment temperature logger installed."